### ISSUE TITLE
Maybe it's time to use Redux?

### ISSUE THREAD

**Issue by olebedev** [olebedev/go-starter-kit#1]
Need time to investigate redux well. Any help with plug in redux are welcome.

**Comment by Laiff** [comment]
I started to work on adding Redux in my fork, see branch redux

**Comment by olebedev** [comment]
@Laiff it looks like you start from outdated HEAD, please merge current HEAD before PR.
Unfortunately there are some conflicts probably...
Main differences are here - https://github.com/olebedev/go-starter-kit/commit/fa26fab9c1acc3fc3cf9f0a6bd2c2894d6c16295, please take a look.

**Comment by jgautheron** [comment]
:+1:

**Comment by deyolfson** [comment]
Hey Friend,
Hope your Thursdays is going well. It was nice to meet you. Here is my
contact info and resume.

David Eyolfson
707-631-6001
deyolfson@gmail.com
http://www.eyolfsondesigns.com
(resume attacted)

Cheers
