### ISSUE TITLE
GSK does not build after fresh pull

### ISSUE THREAD

**Issue by richardcrichardc** [olebedev/go-starter-kit#10]
```
# app/server
src/app/server/app.go:64: undefined: Asset
src/app/server/app.go:65: undefined: AssetDir
src/app/server/react.go:191: undefined: Asset
```

Looks like the file declaring Asset and AssetDir may not have been added when commiting c6c0ff50c8f312d. Or maybe I am just being daft.

**Comment by olebedev** [comment]
Nope, that's okey. Maybe this helps https://github.com/olebedev/go-starter-kit/issues/5.
