### ISSUE TITLE
Build failed following the Readme

### ISSUE THREAD

**Issue by zjx-immersion** [olebedev/go-starter-kit#18]
When i run the go get app is will tips:
~GOPATH git:(master) go get app
# app/server
src/app/server/app.go:65: undefined: Asset
src/app/server/app.go:66: undefined: AssetDir
src/app/server/app.go:72: undefined: Asset
src/app/server/app.go:72: undefined: AssetDir
src/app/server/react.go:185: undefined: Asset

but when i ran the make serve ,it still success. then i ran the go get app, all good.
do you encounter the same situation?

**Comment by olebedev** [comment]
It because at the first time you don't have generated `bindata.go` file. See: https://github.com/olebedev/go-starter-kit/issues/5
