### ISSUE TITLE
go-bindata-assetfs nil pointer

### ISSUE THREAD

**Issue by simonz05** [olebedev/go-starter-kit#25]
I'm getting a nil pointer exception in production mode with the latest go-bindata-assetfs. Last working commit seems to be https://github.com/elazarl/go-bindata-assetfs/commit/d5cac425555ca5cf00694df246e04f05e6a55150

**Comment by olebedev** [comment]
@simonz05 sorry, but I can not produce this bug. I have just checked the deps one more time and didn't get any errors. Could you provide more info code peaces and so on?

**Comment by olebedev** [comment]
@simonz05 I had just found the bug. It seems that it's a case of breaking changes. I would recommend using some dependency management tool to lock dependencies. Actually, I plug in my own into the project. Please, see [install](https://github.com/olebedev/go-starter-kit#install) section for details.

P.S.: I'll see that is the problem with go-bindata-assetfs soon.
