### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:5000

### ISSUE THREAD

**Issue by magj2006** [olebedev/go-starter-kit#27]
when i make serve, the output is :

Error: connect ECONNREFUSED 127.0.0.1:5000
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

i type lsof -i:5000, nothing output.

**Comment by olebedev** [comment]
Could you paste the output of the `env` command?

**Comment by magj2006** [comment]
Thanks so much.
the output is in env_output.txt
[env_output.txt](https://github.com/olebedev/go-starter-kit/files/97745/env_output.txt)

**Comment by olebedev** [comment]
It's strange a bit. I didn't see anything what can be the cause of it. What is output of `go build -o $GOPATH/bin/app`. Is the binary there after this command?

**Comment by magj2006** [comment]
it happened when i modify some file.

i typed  go build -o $GOPATH/bin/app, nothing output.  but i can see app file.

cloud@ubuntu:~/Code/gsk$ ls -l bin/app
-rwxr-xr-x 1 cloud cloud 14010368 Jan 21 12:33 bin/app

**Comment by olebedev** [comment]
Please try to reproduce this [steps](https://github.com/olebedev/go-starter-kit/blob/master/Makefile#L42-L45) and make sure that you have all [dependencies](https://github.com/olebedev/go-starter-kit#dependencies)(particularly `fswatch`) installed.

**Comment by magj2006** [comment]
yea, i do it by your steps: 1. npm i 2.export GOPATH=`pwd` 3.srlt r && srlt e go install {{.Name}}/...  4.make serve
it's good, but when I modify some file,  it output ECONNREFUSED 127.0.0.1:5000 and many restart app...


cloud@ubuntu:~/Code/gsk$ which fswatch
/opt/apps/fswatch/bin/fswatch

**Comment by olebedev** [comment]
Hm, I cannot reproduce this bug because I on Mac OS and it works well for me. 

It looks like that Golang server is terminated but not restarted. Try to do it manually step-by-step from makefile rules with each step total checking.

**Comment by magj2006** [comment]
Okay, I try it.  thanks so much.

**Comment by olebedev** [comment]
Closed. Feel free open it if needed.
