### ISSUE TITLE
Can this run on heroku?

### ISSUE THREAD

**Issue by tonyalaribe** [olebedev/go-starter-kit#3]
Since this uses duktape which is an embeddable C program, would it run on a single process heroku instance?

**Comment by olebedev** [comment]
Hi, @tonyalaribe
Of course this can!
My workflow is: 
- build the linux binary
- push the file to heroku/dokku with [null-buildpack](https://github.com/ryandotsmith/null-buildpack)

That's it.

**Comment by tonyalaribe** [comment]
Thanks @olebedev .  So, no more compiling on heroku, but still convenient
