### ISSUE TITLE
Production builds are including some dev resources

### ISSUE THREAD

**Issue by simonz05** [olebedev/go-starter-kit#31]
`NODE_ENV=production make build` creates a js bundle which is `373K`. Removing the references to `redux-devtools` in client/ and running the same command again reduces the size by `~70K`.

**Comment by EdVanDance** [comment]
[Here's](https://github.com/gaearon/redux-devtools/blob/master/docs/Walkthrough.md#exclude-devtools-from-production-builds) a fix.

**Comment by olebedev** [comment]
Yep, thanks, @EdVanDance. It's just need to import by the condition. Define plugin already there. I'll fix it soon.

**Comment by simonz05** [comment]
Yes, I've used the same docs as a reference for my personal branch of this.

**Comment by olebedev** [comment]
@simonz05, would you send it as a PR?

**Comment by olebedev** [comment]
Need to fix in #28.
