### ISSUE TITLE
Can't get it to boot

### ISSUE THREAD

**Issue by mrmayfield** [olebedev/go-starter-kit#36]
```
Hash: 8771430a13b6b6e77fc1
Version: webpack 1.12.13
Time: 113278ms
     Asset     Size  Chunks             Chunk Names
 bundle.js  1.37 MB       0  [emitted]  bundle
bundle.css  9.44 kB       0  [emitted]  bundle
    + 772 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
/Users/leswan/bin/go-bindata -pkg=main -prefix=server/data -debug -o=server/bindata.go server/data/...
cat: .pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
# github.com/anthony/goreact/server
usage: 6l [options] main.6
  -1	use alternate profiling code
  -8	assume 64-bit addresses
  -B info
    	define ELF NT_GNU_BUILD_ID note
  -C	check Go calls to C code
  -D addr
    	data address
  -E sym
    	entry symbol
  -I interp
    	set ELF interp
  -L dir
    	add dir to library path
  -H head
    	header type
  -K	add stack underflow checks
  -O	print pc-line tables
  -Q	debug byte-register code gen
  -R rnd
    	address rounding
  -S	check type signatures
  -T addr
    	text address
  -V	print version and exit
  -W	disassemble input
  -X name value
    	define string data
  -Z	clear stack frame on entry
  -a	disassemble output
  -c	dump call graph
  -d	disable dynamic executable
  -extld ld
    	linker to run in external mode
  -extldflags ldflags
    	flags for external linker
  -f	ignore version mismatch
  -g	disable go package data checks
  -installsuffix suffix
    	pkg directory suffix
  -k sym
    	set field tracking symbol
  -linkmode mode
    	set link mode (internal, external, auto)
  -n	dump symbol table
  -o outfile
    	set output file
  -r dir1:dir2:...
    	set ELF dynamic linker search path
  -race
    	enable race detector
  -s	disable symbol table
  -shared
    	generate shared object (implies -linkmode external)
  -tmpdir dir
    	leave temporary files in this directory
  -u	reject unsafe packages
  -v	print link trace
  -w	disable DWARF generation
make: *** [/Users/leswan/bin/goreact] Error 2
```

**Comment by olebedev** [comment]
Which version of Golang do you use?

**Comment by kelvinji2009** [comment]
Can't boot too.

[LOG]
---
★  go-starter-kit git:(kdev) »make serve
Hash: b75f147d15b668a79458
Version: webpack 1.12.13
Time: 3183ms
     Asset     Size  Chunks             Chunk Names
 bundle.js  1.35 MB       0  [emitted]  bundle
bundle.css  9.44 kB       0  [emitted]  bundle
    + 652 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
/Users/kelvinji/mitnick/tools/go/bin/go-bindata -pkg=main -prefix=server/data -debug -o=server/bindata.go server/data/...
cat: .pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
can't load package: package /Users/kelvinji/mitnick/dev/github/go-starter-kit/server: import "/Users/kelvinji/mitnick/dev/github/go-starter-kit/server": cannot import absolute path
make: *** [/Users/kelvinji/mitnick/tools/go/bin/go-starter-kit] Error 1

---
[ENV]
go-starter-kit git:(kdev) »go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/kelvinji/mitnick/tools/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"

**Comment by kelvinji2009** [comment]
@olebedev BTW, i am using `srlt` following the build guide from README.md

**Comment by olebedev** [comment]
@kelvinji2009, go 1.4.2 is not working with _GO15VENDOREXPERIMENT_, please use Go 1.5.3 instead.

**Comment by kelvinji2009** [comment]
@olebedev Okay, got it. Thanks.

**Comment by magj2006** [comment]
@olebedev There is a same problem. 
1. go version: go1.5.3 linux/amd64
2. I run srlt restore, and vendor directory is created.
ls -l vendor
drwxrwxr-x 12 cloud cloud 4096 Feb 22 15:54 github.com
drwxrwxr-x  3 cloud cloud 4096 Feb 22 15:54 golang.org
drwxrwxr-x  4 cloud cloud 4096 Feb 22 15:54 gopkg.in
3. I run make serve
...
/home/cloud/Code/go/bin/go-bindata -pkg=main -prefix=server/data -debug -o=server/bindata.go server/data/...
make: /home/cloud/Code/go/bin/go-bindata：Command cann't find
make: *** [server/bindata.go] Error 127

Please Help!

**Comment by olebedev** [comment]
@magj2006, sure. You need to install `go-bindata` directly. Run this command to do it: `go install github.com/jteeuwen/go-bindata`. I have just fixed `README.md`. Take a look it again.

**Comment by magj2006** [comment]
@olebedev I installed go-bindata, and run make serve again, output : 
server/app.go:8:2: cannot find package "github.com/elazarl/go-bindata-assetfs" in any of:
	/opt/apps/go/src/github.com/elazarl/go-bindata-assetfs (from $GOROOT)
	/home/cloud/Code/go/src/github.com/elazarl/go-bindata-assetfs (from $GOPATH)
server/app.go:9:2: cannot find package "github.com/itsjamie/go-bindata-templates" in any of:
	/opt/apps/go/src/github.com/itsjamie/go-bindata-templates (from $GOROOT)
	/home/cloud/Code/go/src/github.com/itsjamie/go-bindata-templates (from $GOPATH)
server/api.go:6:2: cannot find package "github.com/labstack/echo" in any of:
	/opt/apps/go/src/github.com/labstack/echo (from $GOROOT)
	/home/cloud/Code/go/src/github.com/labstack/echo (from $GOPATH)
server/app.go:13:2: cannot find package "github.com/labstack/echo/middleware" in any of:
	/opt/apps/go/src/github.com/labstack/echo/middleware (from $GOROOT)
	/home/cloud/Code/go/src/github.com/labstack/echo/middleware (from $GOPATH)
server/app.go:10:2: cannot find package "github.com/nu7hatch/gouuid" in any of:
	/opt/apps/go/src/github.com/nu7hatch/gouuid (from $GOROOT)
	/home/cloud/Code/go/src/github.com/nu7hatch/gouuid (from $GOPATH)
server/app.go:14:2: cannot find package "github.com/olebedev/config" in any of:
	/opt/apps/go/src/github.com/olebedev/config (from $GOROOT)
	/home/cloud/Code/go/src/github.com/olebedev/config (from $GOPATH)
server/react.go:13:2: cannot find package "gopkg.in/olebedev/go-duktape-fetch.v2" in any of:
	/opt/apps/go/src/gopkg.in/olebedev/go-duktape-fetch.v2 (from $GOROOT)
	/home/cloud/Code/go/src/gopkg.in/olebedev/go-duktape-fetch.v2 (from $GOPATH)

so, need to add vendor directory to to env path ?

**Comment by kelvinji2009** [comment]
```
IMPORT_PATH   = $(shell echo `pwd` | sed "s|^$(GOPATH)/src/||g")
```

```
go build -ldflags '$(LDFLAGS)' -o $@ $(IMPORT_PATH)/server

```
>>>>if this, we must put the project into $GOPATH/src? But usually  we put the code in anywhere we want.

---

★  go-starter-kit git:(kdev) »make serve
Hash: b75f147d15b668a79458
Version: webpack 1.12.13
Time: 3061ms
     Asset     Size  Chunks             Chunk Names
 bundle.js  1.35 MB       0  [emitted]  bundle
bundle.css  9.44 kB       0  [emitted]  bundle
    + 652 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
/Users/kelvinji/.gvm/pkgsets/go1.5.3/global/bin/go-bindata -pkg=main -prefix=server/data -debug -o=server/bindata.go server/data/...
cat: .pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
can't load package: package /Users/kelvinji/mitnick/dev/github/go-starter-kit/server: import "/Users/kelvinji/mitnick/dev/github/go-starter-kit/server": cannot import absolute path
make: *** [/Users/kelvinji/.gvm/pkgsets/go1.5.3/global/bin/go-starter-kit] Error 1

**Comment by olebedev** [comment]
@kelvinji2009, yup. Put the code into somewhere in '$GOPATH/src'.

**Comment by mrmayfield** [comment]
Okay I'm only working with Go on a weekend project, I will come back to this though, for the record I am running 1.4.2 at the moment but will upgrade and see what happens on Saturday.

**Comment by olebedev** [comment]
As I see all that you need just update go version up to 1.6. Go's 1.4
linker doesn't accept LDFLAGS which are defined at this moment in Makefile.

On Wed, Feb 24, 2016 at 9:11 AM, Anthony Mayfield <notifications@github.com>
wrote:

> Okay I'm only working with Go on a weekend project, I will come back to
> this though, for the record I am running 1.4.2 at the moment but will
> upgrade and see what happens on Saturday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olebedev/go-starter-kit/issues/36#issuecomment-188055989>
> .
>



-- 
Oleg Lebedev
+7 922 1505553
