### ISSUE TITLE
unrecognized  package

### ISSUE THREAD

**Issue by sailei1** [olebedev/go-starter-kit#4]
go get app/...
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context"
package golang.org/x/net/publicsuffix: unrecognized import path "golang.org/x/net/publicsuffix"

make  serve
cleaned
 62% 62/71 build modulesContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Container#remove is deprecated. Use Container#removeChild
 64% 64/71 build modulesNode#before is deprecated. Use Node#raws.before
Hash: ad1be354968dcbacaf4f  
Version: webpack 1.12.1
Time: 9441ms
                                        Asset       Size      Chunks             Chunk Names
building@58ca48db9e7cd1cfa3aeebcb77db21cf.jpg     204 kB              [emitted]  
 favicon@71e4b47eb774474184d8ac2302d45f3e.ico  205 bytes              [emitted]  
                       ../../bundle.server.js    1.11 MB        0, 1  [emitted]  ../../bundle.server
                                    bundle.js    1.11 MB        1, 0  [emitted]  bundle
                                   bundle.css    4.23 kB  0, 1, 1, 0  [emitted]  ../../bundle.server, bundle
    + 358 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 3 hidden modules
/Users/zhangsailei/golang/bin/go-bindata -pkg=server -prefix=src/app/server/data -debug -o=src/app/server/bindata.go src/app/server/data/...
cat: .pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
can't load package: package app: cannot find package "app" in any of:
	/usr/local/go/src/app (from $GOROOT)
	/Users/zhangsailei/golang/src/app (from $GOPATH)
make[1]: *** [restart] Error 1
make: *** [serve] Error 2

**Comment by olebedev** [comment]
Could you provide output of this command - `echo $GOPATH && pwd`, executed in project folder?

**Comment by sailei1** [comment]
export GOARCH=amd64
export GOOS=darwin
export GOPATH=$HOME/golang
export GOROOT=/usr/local/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

**Comment by sailei1** [comment]
sai:~ zhangsailei$ echo $GOPATH && pwd
/Users/zhangsailei/golang
/Users/zhangsailei

**Comment by olebedev** [comment]
It looks like you didn't export new GOPATH.
Try this in project folder:
```
$ export GOPATH=`pwd`
$ go get app/...
$ go get github.com/jteeuwen/go-bindata/...
```
Check [install](https://github.com/olebedev/go-starter-kit#install) section for more information.

I leave this issue open, while I don't sure that the problem is just correct GOPATH. Please, let me know.

**Comment by sailei1** [comment]
It's   just correct GOPATH , put  in  $HOME/golang/src    it's fine

**Comment by olebedev** [comment]
Ok :+1: 
It is still recommended to use separate GOPATH, at least for this project.
