### ISSUE TITLE
cannot import absolute path

### ISSUE THREAD

**Issue by wenxingxing2011** [olebedev/go-starter-kit#43]
sorry ,i am a newerr. when i make serve,i got this problem. 
my system is win10 and have cygwin env.

![image](https://cloud.githubusercontent.com/assets/8664961/14377589/131cee0e-fda3-11e5-9104-d933642ea5a8.png)
![image](https://cloud.githubusercontent.com/assets/8664961/14377602/29e36906-fda3-11e5-90c9-b03c3bf01340.png)
![image](https://cloud.githubusercontent.com/assets/8664961/14377756/0e2a04d0-fda4-11e5-90d2-56fb7884977c.png)
![image](https://cloud.githubusercontent.com/assets/8664961/14377764/1999fd5c-fda4-11e5-9d57-88df588c1f58.png)

sorry my poor english, best regards

**Comment by olebedev** [comment]
It won't works on Windows/Cygwin because of backslashed `$GOPATH`. I would recommend trying a native command line interpreter which is released a couple days ago. Meaning, ubuntu within Windows 10 natively.  Please let me know how it works If you try it.

Another option is using dockered workspace.
