### ISSUE TITLE
[Document]I think there should be some document on the onEnter part...

### ISSUE THREAD

**Issue by maxsonic** [olebedev/go-starter-kit#49]
I have encountered lots of bugs related with onEnter method. All those bugs are caused by my code, but I see no error message on the console:(..

To successfully debug the bug in the onEnter method, one should be warned that even a small syntax error will result in malfunction and the server side rendering will not work. Hence, one should run the code on the client side first and then move to the onEnter part.

And the router params should be written done on the readme.md to tell the users where to find the url parameters, i.e. nextState.params.xxx.

I would like to say this is really a nice starer kit :)

**Comment by olebedev** [comment]
Hi @maxsonic,

thanks for your message.

> I have encountered lots of bugs related with onEnter method. All those bugs are caused by my code, but I see no error message on the console:(..

Actually, you should see the error message at the client-side, if the problems was caught at server-side. Have a look - [this](https://github.com/olebedev/go-starter-kit/blob/master/server/data/templates/react.html#L10) and [this](https://github.com/olebedev/go-starter-kit/blob/master/server/react.go#L53-L60).

> ... Hence, one should run the code on the client side first and then move to the onEnter part.

Isomorphic render assumes that you got already rendered page to the browser first.

> And the router params should be written done on the readme.md to tell the users where to find the url parameters, i.e. nextState.params.xxx.

I really don't mind if good people will send me pull request.

> I would like to say this is really a nice starer kit :)

Glad to hear. Thank you.
