### ISSUE TITLE
command "make serve" is failed.

### ISSUE THREAD

**Issue by TianDaGe** [olebedev/go-starter-kit#53]
![1](https://cloud.githubusercontent.com/assets/15997235/17772441/bd4e5a86-64fd-11e6-9ffe-88afbf810628.png)

![1](https://cloud.githubusercontent.com/assets/15997235/17772472/f1d75a0a-64fd-11e6-9037-68c4b4c1080a.png)

Hello, I tried to make server by using go-starter-kit.
I success "slrt restore" comand and it made vendor directory in go-start-kit directory.
Actually, I copied and past your released slrt binary file to the go-start-kit root directory and execute "slrt command".
Next, I installed MINGW for GNUMake in the windows. and tried make command.
In that time, I faced the above issue. What is wrong with it?

PS: I tried on the mac os too, but issue is same.

**Comment by olebedev** [comment]
Hi @TianDaGe,
sorry, windows are not supported for now. Please, use some unix-like system.

**Comment by TianDaGe** [comment]
currently, I am trying on mac os x. but issue is same
<img width="578" alt="screen shot 2016-08-18 at 8 23 10 pm" src="https://cloud.githubusercontent.com/assets/15997235/17773499/5e980dc8-6581-11e6-9e45-09cfb3a59c84.png">

**Comment by iKonrad** [comment]
I had the same issue and it was because I had my repo outside of the Go workspace.
Make sure to clone your repo project to: $GOPATH/src/github.com/<username>/<Projectname>/
