### ISSUE TITLE
update echo web framework

### ISSUE THREAD

**Issue by TianDaGe** [olebedev/go-starter-kit#54]
Thanks, Olebedev.
I installed go-starter-kit on my mac book after check some issues that posted before.
I have one request,
Echo is updated to v2.0, there are some issues to update echo in go-starter-kit.
Please help me, can you update the go-starter-kit with echo 2.0?

Thanks,

**Comment by olebedev** [comment]
Sure, it's a good practice to keep all project's dependencies up-to-date. Due to time lack, I cannot do it quickly. Any pull request will be a really appreciated.

**Comment by TianDaGe** [comment]
Hello, Sir
I am facing below issues.

<img width="667" alt="screen shot 2016-08-22 at 9 56 05 am" src="https://cloud.githubusercontent.com/assets/15997235/17841761/ac74efb4-684e-11e6-9875-10939cea5ce5.png">
// Initialize the application
	app := &App{
		Conf:   conf,
		Engine: engine,
		API:    &API{},
		React: NewReact(
			conf.UString("duktape.path"),
			conf.UBool("debug"),
			engine,
		),
	}
... ...
<img width="828" alt="screen shot 2016-08-22 at 9 57 48 am" src="https://cloud.githubusercontent.com/assets/15997235/17841767/b5a912e0-684e-11e6-8d6c-ffca57b8de8b.png">
// Map app struct to access from request handlers
	// and middlewares
	app.Engine.Use(func(c echo.Context) error {
		c.Set("app", app)
		return nil
	})

:) I am a golang beginner. How can I fix it? I have fixed other some issues.
Looking forward to hearing from you soon.
Thanks,
Best Regards,

**Comment by rtuin** [comment]
I've found a fork that upgrades to echo v2 here: https://github.com/phuongvu/go-starter-kit/commit/43f456fe8b8f387f1f27c06100358c4f40b2ab7c
I'm not sure what the quality is, but perhaps this is a good starting point!

**Comment by olebedev** [comment]
@rtuin, 

https://github.com/phuongvu/go-starter-kit/commit/43f456fe8b8f387f1f27c06100358c4f40b2ab7c looks good to me.

**Comment by rtuin** [comment]
I created #55 to address the upgrade to echo v2

**Comment by flamedmg** [comment]
Echo V3 is out.

**Comment by moleculethor** [comment]
Hi, I am fairly new to Go, but base on the work from @phuongvu I tried to update Echo to v3. It seems to work for me (so far). 

If anybody wants to check it out. 
I apologies in advance, my knowledge of github and git in general is pretty limited.

gitlab.com/theloin/go-starter-kit

**Comment by olebedev** [comment]
#65
