### ISSUE TITLE
Deploy to openshift host

### ISSUE THREAD

**Issue by rushstrike** [olebedev/go-starter-kit#59]
Openshift now supports Go. Anyone has an idea on how to configure this starter kit to make it deployable to openshift? Thank you in advance.

https://github.com/smarterclayton/openshift-go-cart

I need to combine the link above with this project for deployment I think.

**Comment by olebedev** [comment]
The best way to deploy this project is to build a single binary artifact, as it already configured and push the executable wherever you want. 

Example hiw to build you could find in readme.md and werker.yml

However, I'm not sure that OpenShift supports binary executable files.
