### ISSUE TITLE
Makefile:19: *** target pattern contains no `%'.  Stop.

### ISSUE THREAD

**Issue by apurohitm** [olebedev/go-starter-kit#62]
I  am transitioning from Java to Go, trying to build a web application with some UI. 

After cloning repo I am running make install, but I am getting this error. 

Makefile:19: *** target pattern contains no `%'.  Stop.

Please let me know if I have missed anything.

**Comment by olebedev** [comment]
Hi @apurohitm,
which Golang version do you use?

**Comment by apurohitm** [comment]
Thanks for reply @olebedev 

Below is the version. 

go version go1.7.3 darwin/amd64

**Comment by joelnb** [comment]
@apurohitm do you have a colon in your `$GOPATH`? I don't personally use it like that but it is a valid configuration as described [here](https://stackoverflow.com/questions/36017724/can-i-have-multiple-gopath-directories). If I add one I can reproduce this error:

```bash
mkdir /tmp/go
export GOPATH=$GOPATH:/tmp/go
make install
```

The reason for this is similar to the answer [here](https://stackoverflow.com/questions/32125387/make-syntax-of-static-pattern-rules-error-target-pattern-contains-no).
