### ISSUE TITLE
Setup Instructions Not Working

### ISSUE THREAD

**Issue by epalaima** [olebedev/go-starter-kit#67]
Hi, I cloned the repo and ran make install, which does not return any errors, but when I run make serve I get:

'go install /Users/Emmett/Desktop/go-starter-kit/vendor/github.com/olebedev/on
can't load package: package /Users/Emmett/Desktop/go-starter-kit/vendor/github.com/olebedev/on: import "/Users/Emmett/Desktop/go-starter-kit/vendor/github.com/olebedev/on": cannot import absolute path
make: *** [/bin/on] Error 1

Any idea what is causing this? Thanks!

**Comment by olebedev** [comment]
Hi @epalaima, 

what is the output of `go env` command?

**Comment by epalaima** [comment]
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/Emmett/golang"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by olebedev** [comment]
Move project folder into GOPATH.
