### ISSUE TITLE
support for code splitting

### ISSUE THREAD

**Issue by fanky5g** [olebedev/go-starter-kit#69]
Been trying too hard to achieve code splitting but can't get my way around the window undefined error when rendering on the server.

Is there any way to achieve code splitting using webpack's require.ensure.
or probably another method to circumvent that error.

**Comment by olebedev** [comment]
Obviously, server cannot handle source scriot loading vua scropt html tag. Use different bundles for client and server.

**Comment by fanky5g** [comment]
I'll try to hack that, however if you could show an example to point me in the right direction I'd be grateful.
