### ISSUE TITLE
Restart go server on change

### ISSUE THREAD

**Issue by girishso** [olebedev/go-starter-kit#7]
Is it possible to auto restart the go server on .go file changes? The only way I know right now is restarting `make serve`.

May be using https://github.com/codegangsta/gin or my current favorite https://github.com/alexch/rerun

**Comment by olebedev** [comment]
Actually, it should works with `make serve`. There is the rule that [runs fswatch](https://github.com/olebedev/go-starter-kit/blob/master/Makefile#L31) to looking for changes. 

What is your dev environment?

**Comment by girishso** [comment]
I am on Mac OS X Yosemite. Somehow it's not working for me!

**Comment by girishso** [comment]
Oh I didn't have `fswatch`... `brew install fswatch` fixed it!

Thank you!

**Comment by olebedev** [comment]
:+1:
