### ISSUE TITLE
replace hot-proxy.js with webpack-dev-server

### ISSUE THREAD

**Issue by tracker1** [olebedev/go-starter-kit#75]
Webpack-dev-server already has an option to reverse proxy...  Unless you are proxying websockets to the go server, in which case there's some changes pending iirc.

**Comment by olebedev** [comment]
I don remember, exactly, but seems there were some limitations to plug webpack-dev-server in. Are you sure that all used functionality built in webpack-dev-server and we could migrate to it easily?

Anyway, the price is yet another file in the root folder(`./hot.proxy.js`), nothing else.

**Comment by tracker1** [comment]
The main limitation I've seen is that websockets won't be proxied... I'm using it right now, and the passthrough is for anything that isn't served by webpack-dev-server is passed through...

My devserver config...

    {
      hot: true,
      overlay: false,
      noInfo: true,

      publicPath: '/client/',

      proxy: {
        '**': `http://localhost:${API_PORT}/`,
      },
      stats: { colors: true },
    }

**Comment by olebedev** [comment]
Thanks @tracker1!

But I would prefer to let be as it was.

**Comment by abzfarah** [comment]
Hey guys

Now that webpack dev server supports WS, what do you think about replacing hot-proxy?
