### ISSUE TITLE
Can you do some api for user login&logout in starter-kit？

### ISSUE THREAD

**Issue by xiongxin** [olebedev/go-starter-kit#8]
Can you do some api for user login&logout in starter-kit？
1. base user table in database
2. api for login&reg&logout

so we can easier to start coding project.

**Comment by olebedev** [comment]
Thanks @xiongxin for your suggestion.
I don't think that is good idea to add some authentication stuff. It is up to you how to organize your data flow and which database to use. This is just starter kit to show how-to. This is not a framework.
