### ISSUE TITLE
Server remains in background on exit

### ISSUE THREAD

**Issue by nazwa** [olebedev/go-starter-kit#84]
Stopping `make serve` with `ctrl + c` leaves the go server running in background.
![](https://maciej.im/u/MTY1OA/2017-05-08-00-23-39.png)

And it continues serving (and outputting) requests:
![](https://maciej.im/u/MTY1Nw/2017-05-08-00-22-03.png)

Unfortunately this is way beyond my make skills to fully dig into myself. All the other processes seem to quit just fine. Not sure what's different about the server.

This might be completely unrelated, but during the initial startup it does say that it couldn't find the right process. Leftover pid from the previous run?
![](https://maciej.im/u/MTY1OQ/2017-05-08-00-28-46.png)

```
Ubuntu 16.04.2 LTS running in WSL
```

**Comment by olebedev** [comment]
Seems something went wrong. Could you kill _go-starter-kit_ server's process and run `make serve` again? What is the result?

**Comment by nazwa** [comment]
If I **do** manually kill the server process - `make serve` starts as if nothing happened.

If I **don't** manually kill the server process, `make serve` also starts as if nothing happened, and kills the server using pid saved in the file

It's not the end of the world, but it is a bit inconvenient to have the orphaned process running 😄

**Comment by nazwa** [comment]
Seems to have fixed itself 😕 No clue what was happening there.
