### ISSUE TITLE
panic: TypeError: Object has no member 'assign' at S 

### ISSUE THREAD

**Issue by whitebook** [olebedev/go-starter-kit#85]
I just tried to run make serve 

Here is the output. I tried to debug, but I am not sure where the issue is.

Hash: 070ca457e163c58c8dc8  
Version: webpack 1.15.0
Time: 4546ms
     Asset     Size  Chunks             Chunk Names
 bundle.js  1.18 MB       0  [emitted]  bundle
bundle.css  9.11 kB       0  [emitted]  bundle
    + 335 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
/apps/go/bin/go-bindata -pkg=main -prefix=server/data -debug -o=server/bindata.go server/data/...
/bin/sh: line 0: kill: (7772) - No such process
restart the app...
⇛ http server started on [::]:5000
==> 🌎  Listening on port 5001. Open up http://localhost:5001/ in your browser.
init JSVM static/build/bundle.js
panic: TypeError: Object has no member 'assign' at S (bundle.js:31799:6781(38))

goroutine 35 [running]:
main.newJSVM.func1(0xc4201b2000)
	/apps/go/src/github.com/whitebook/leasing/server/react.go:199 +0x4d1
github.com/whitebook/leasing/vendor/github.com/dop251/goja_nodejs/eventloop.(*EventLoop).RunOnLoop.func1()
	/apps/go/src/github.com/whitebook/leasing/vendor/github.com/dop251/goja_nodejs/eventloop/eventloop.go:109 +0x31
github.com/whitebook/leasing/vendor/github.com/dop251/goja_nodejs/eventloop.(*EventLoop).run(0xc42017fe00, 0xc4201ce001)
	/apps/go/src/github.com/whitebook/leasing/vendor/github.com/dop251/goja_nodejs/eventloop/eventloop.go:116 +0x77
created by github.com/whitebook/leasing/vendor/github.com/dop251/goja_nodejs/eventloop.(*EventLoop).Start
	/apps/go/src/github.com/whitebook/leasing/vendor/github.com/dop251/goja_nodejs/eventloop/eventloop.go:87 +0x44
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Error: connect ECONNREFUSED 127.0.0.1:5000
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

**Comment by whitebook** [comment]
I just wanted to mention

I am on OSX.

GO Version: go version go1.8.1 darwin/amd64
Node Version: v7.10.0

**Comment by olebedev** [comment]
Is this output for the blank starter kit?
Note: goja supported only ES5 spec and `Object.assign` is not a part of ES5 spec.

**Comment by whitebook** [comment]
This is the for the blank starter kit

**Comment by olebedev** [comment]
Okay, I will check this soon. Thanks to the report.

Oleg Lebedev
+7 922 1505553

**Comment by whitebook** [comment]
Thanks for the fix it is resolved now.
