### ISSUE TITLE
How to make redux-devtools work?

### ISSUE THREAD

**Issue by zhangmaku** [olebedev/go-starter-kit#88]
```
        import DevTool from '../dev-tool';
         ...
         ...
          }
        ]} />
      <DevTool />
      <h1 className={example}>
        Hot Reloadable <br />
        Golang + React + Redux + Css-Modules
```
error
`Redux DevTools could not render. Did you forget to include DevTools.instrument() in your store enhancer chain before using createStore()?`

**Comment by iKonrad** [comment]
Here's my createStore part with devTools:
```
    return reduxCreateStore(
        reducers,
        state,
        compose(
            applyMiddleware.apply(null, middlewares),
            typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ? window.devToolsExtension() : f => f
        )
    );
```

you just need to add this line `typeof window === 'object' && typeof window.devToolsExtension !== 'undefined' ? window.devToolsExtension() : f => f` to `compose` when creating a store and it should work
