### ISSUE TITLE
import css not work?

### ISSUE THREAD

**Issue by zhangmaku** [olebedev/go-starter-kit#91]
```
import ReactTable from 'react-table'
import 'react-table/react-table.css'
 ...
 ...
render (){
  return(
 ...
 ...
 ...
  <ReactTable
    data={data}
    columns={columns}
  />
  )
}
```

ReactTable can't load css style, how can I do?

![image](https://user-images.githubusercontent.com/25602778/27003057-6de7f92a-4e22-11e7-9be9-82a6e810d89b.png)

**Comment by olebedev** [comment]
Hi @zhangmaku, by `webpack.config.js`.  There is nothing special.
