### ISSUE TITLE
Port 5001

### ISSUE THREAD

**Issue by abzfarah** [olebedev/go-starter-kit#93]
Just wondering why is it that you can load the browser on port 5001? I've been looking for where you set this config but can't find it. When I search the repo the only reference I get is the readme.

**Comment by joelnb** [comment]
I think you should look in hot.proxy.js (in the root of the repo) - specifically the line where it does 'port++' (after setting it to 5000 if you didn't specify another port through the env var).

Sorry for the lack of links as I'm on mobile but hopefully this should help you find what you want.

**Comment by abzfarah** [comment]
@joelnb thanks
