### ISSUE TITLE
Question: Why echo ? How about today ?

### ISSUE THREAD

**Issue by ferhatelmas** [olebedev/go-starter-kit#96]
Hi Oleg,

I'm in a phase to pick echo vs gin. 

It seems gin was in use before, which is replaced by echo. I would appreciate if you could provide some insights about this change. 

Moreover, both projects are moving so reasons at that time might not be valid anymore so how would you consider your options today?

Thanks in advance!

**Comment by olebedev** [comment]
Hi @ferhatelmas,

I found echo’s api more elegant and solid, meanwhile, gin’s api grew spontaneously and a bit ill-conceived. 

Well, today i would pick swagger or graphql(both with code generation) b/c documentation and flexibility is matter nowadays.

**Comment by ferhatelmas** [comment]
@olebedev Thanks for answer. Any preference for graphql implementation and why ?

**Comment by olebedev** [comment]
@ferhatelmas, just an option from two possible. GraphQL shifts complexity from backend to frontend, it's not a silver bullet.

**Comment by ferhatelmas** [comment]
@olebedev sure. Actually, we have a team, more inclined to frontend (3 vs 1). Thus, it might be a good point to get started if we want to investigate further.
